name: Pull Request Security Check
on: [pull_request]

jobs:
  SourceCodeAnalysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep Differential
        # On ajoute --error pour forcer le crash si une faille est trouvée
        run: semgrep scan --config .semgrep --baseline-commit ${{ github.event.pull_request.base.sha }} --json --output semgrep-diff.json --error
        # ON A SUPPRIMÉ "continue-on-error: true" ICI !

      - name: Upload Semgrep Artifact
        # On ajoute "if: always()" pour que le rapport soit quand même sauvegardé, même si le step a crashé (rouge)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-differential-report
          path: semgrep-diff.json
