name: security

# Le déclencheur est tout seul
on:
  workflow_dispatch:

# Les permissions sont à la racine (alignées tout à gauche)
permissions:
  actions: read
  security-events: write
  contents: read

# Les jobs sont à la racine (alignés tout à gauche)
jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysis_Full.sarif
            ./
        continue-on-error: true

      - name: Upload OSV SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysis_Full.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - uses: actions/checkout@v4

      - name: run semgrep
        run: semgrep scan --config .semgrep --sarif --output SourceCodeAnalysis.sarif
        continue-on-error: true

      - name: Upload Semgrep SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysis.sarif
