name: security
on:
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1.9.0
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true
      - name: Send report to security dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: DependenciesAnalysisFull.sarif

  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:latest
    steps:
      - uses: actions/checkout@v4
      - name: run semgrep
        run: semgrep scan --config .semgrep --sarif --output SourceCodeAnalysis.sarif
        continue-on-error: true
      - name: Send report to security dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: SourceCodeAnalysis.sarif
